/**
 * Copyright (c) HashiCorp, Inc.
 * SPDX-License-Identifier: MPL-2.0
 */

// generated by cdktf get
Object.defineProperty(exports, 'dataExternal', { get: function () { return require('./data-external'); } });
Object.defineProperty(exports, 'provider', { get: function () { return require('./provider'); } });

