// generated by cdktf get
Object.defineProperty(exports, 'dataExternal', { get: function () { return require('./data-external'); } });
Object.defineProperty(exports, 'provider', { get: function () { return require('./provider'); } });

